config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # Calendars route
  resources :resources

  get 'calendars', to: 'calendars#calendars', as: :calendar_view
  get '/redirect', to: 'calendars#redirect', as: :calendar_redirect
  get '/callback', to: 'calendars#callback'

  resources :events do
    member do
      patch 'update_show', to: 'events#update_show'
    end
  end

  # Health check route
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Session management routes
  get 'logout', to: 'session_manager#logout', as: :logout
  get '/auth/google_oauth2/callback', to: 'session_manager#google_oauth_callback_handler'
  get '/auth/failure', to: 'session_manager#google_oauth_failure_handler'

  # Import Data route
  get '/import/data/', to: 'import_data#index', as: :import
  delete '/import/data/delete', to: 'import_data#delete_data', as: :import_delete
  post '/import/data/upload', to: 'import_data#upload_data', as: :import_upload

  # Project Hub routes
  get '/project_hub', to: 'project_hub#index', as: :project_hub
  get '/project_management_hub', to: 'project_management_hub#index', as: :project_management_hub

  # Project Hub routes
  get 'view_score', to: 'score#index', as: :view_score
  patch 'update_score', to: 'score#update', as: :update_score

  resources :projects do # rubocop:disable Metrics/BlockLength
    get 'dashboard', to: 'project_management_hub#dashboard', as: 'dashboard'
    get 'team_management', to: 'project_management_hub#team', as: 'team_management'
    get 'task_management', to: 'task_management#index', as: 'task_management'
    post 'add_student', to: 'project_management_hub#add_student', as: 'add_student'
    delete 'remove_student', to: 'project_management_hub#remove_student', as: 'remove_student'

    # Student routes related to project
    get 'team', to: 'team_info#index', as: 'view_team'

    # Project
    get 'edit_project', to: 'project_management_hub#edit', as: 'edit_project'
    patch 'update_project', to: 'project_management_hub#update', as: 'update_project'
    delete 'delete_project', to: 'project_management_hub#destroy', as: 'destroy'

    # Students
    resources :students, only: %i[show] do
      get 'tasks', to: 'project_hub#view_tasks', as: 'view_tasks'
      get 'show_milestones', to: 'project_hub#show_milestones', as: :show_milestones
      get 'timeline', to: 'project_hub#timeline', as: 'timeline'
      resources :tasks, only: %i[update] do
        member do
          patch 'update_status', to: 'project_hub#update_task_status', as: 'update_task_status'
        end
      end
    end

    # Nested resources for resources management
    resources :resources, only: %i[new create index destroy] do
      member do
        get :download # This allows downloading a specific resource
        get :open
      end
    end

    # Nested resources for milestones management
    resources :milestones, only: %i[index create edit update destroy] do
      member do
        patch 'update_status', to: 'milestones#update_milestone_status', as: 'update_milestone_status'
      end
    end

    resources :users do
      resources :tasks, only: %i[create update destroy], controller: 'task_management'
    end
  end

  # Settings route
  get '/settings', to: 'settings#index', as: :settings

  post '/create_project', to: 'project_management_hub#create_project', as: :create_project

  # Defines the root path route ("/")
  root 'landing_page#index'

  # Score routes
  # get '/score/index', to: 'score#index', as: :view_score
  # patch '/score/update', to: 'score#update', as: :update_score

  # Event routes
  # resources :events
  # get '/events', to: 'event#index', as: :events
  # post '/events', to: 'event#create', as: :create_event
  # get '/events/:id/edit', to: 'event#edit', as: :edit_event
  # patch '/events/:id', to: 'event#update', as: :update_event
  # delete '/events/:id', to: 'event#destroy', as: :destroy_event

  # patch 'update_event', to: 'event#update', as: 'update_event'

  # Catch-all route for handling 404s
  match '*path', to: 'application#not_found', via: :all
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  # model code here
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# A controller for events banner
class EventsController < ApplicationController
  before_action :set_event, only: %i[edit update destroy]

  def index
    @events = Event.all
    @event = Event.new

    render :index
  end

  def create
    @events = Event.update_all(show: false) # rubocop:disable Rails/SkipsModelValidations
    @event = Event.new(event_params.merge(show: true))
    if @event.save
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      @events = Event.all
      render :index
    end
  end

  def edit
    @event = Event.find(params[:id])
    @events = Event.all
    render :index # This will render the index view with the form populated with @event data
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path, notice: 'Event was successfully updated.'
    else
      flash[:error] = 'Failed to update event'
      @events = Event.all
      render :index
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully destroyed.'
  end

  def update_show
    @event = Event.find(params[:id])
    show_status = params[:show] == '1' # Checkbox sends "1" when checked, "0" when unchecked

    if show_status
      Event.update_all(show: false) # Set all other events to false
      @event.update(show: true)
      message = 'Event was successfully broadcasted.'
    else
      @event.update(show: false)
      message = 'Broadcasting was turned off for this event.'
    end

    redirect_to events_path, notice: message # Redirect to refresh the page and show the updated status
  end

  private

  def set_event
    @events = Event.all
  end

  def event_params
    params.require(:event).permit(:title, :description)
  end
end

app/helpers/event_helper.rb
# frozen_string_literal: true

# Events helper
module EventHelper
end

app/views/events/index.html.erb
<div class="fluid-container p-5">
  <div class="d-flex justify-content-between align-items-center">
    <h3>
      Event Management
    </h3>
  </div>
  <div class="row mt-4">
    <div style="margin-right: 80px;"class="col-md-6"> 
      <h5 class="mb-4">Events</h5>
      <ul class="list-group mb-4 user-list-group" id="events_list">
        <% @events.order(updated_at: :desc).each do |event| %>         
            <li class="card text-bg-light mb-3">
            <div class="card-header d-flex justify-content-between">
                <span>
                    <%= event.title %>
                </span>
                <span class="d-flex justify-content-between w-10">
                    <%= link_to 'Edit', edit_event_path(event), class: "btn btn-primary btn-sm me-1" %>
                    <%= button_to 'Delete',event_path(event), 
                            method: :delete,  
                            onclick: "return confirm('Are you sure you want to delete #{event.title}?')",
                            class: 'btn btn-danger btn-sm me-1' %>
                </span>
            </div>
            <div class="card-body">
            <p><%= event.description %></p>
            <%= form_with url: update_show_event_path(event), method: :patch, local: true do |form| %>
              <div class="form-check form-switch">
                <input type="hidden" name="show" value="0">
                <%= form.check_box :show, 
                                  { class: "form-check-input", 
                                    checked: event.show, 
                                    role: "switch", 
                                    id: "flexSwitchCheckDefault-#{event.id}", 
                                    onchange: "this.form.submit()", 
                                    name: "show" }, 
                                  '1', 
                                  '0' %>
                <label class="form-check-label" for="flexSwitchCheckDefault-<%= event.id %>">Broadcast Event</label>
              </div>
            <% end %>
            </div>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="col-md-5">
      <h5 class="mb-4"><%= @event.persisted? ? "Edit Event" : "Create a New Event" %></h5>
    <%= form_with(model: @event, local: true) do |form| %>
      <div class="form-group mb-3">
        <label for="event_title">Title</label>
        <%= form.text_field :title, required: true, class: "form-control", id: "event_title"%>
      </div>
      <div class="form-group mb-3">
        <label for="event_description">Description</label>
        <%= form.text_area :description, class: "form-control", id: "event_description"%>
      </div class="d-flex">
        <%= form.submit @event.persisted? ? "Update Event" : "Create Event", class: "btn btn-primary mt-3" %>
      <% if @event.persisted? %>
        <%= link_to 'Cancel', events_path, class: "btn btn-secondary mt-3" %>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>